### PR TITLE
add basic-vpc to federalist s3 broker

### PR DESCRIPTION
**Pull request by drewbo**
## Changes proposed in this pull request:
- Adds the `basic-vpc` plan to the federalist s3 broker (after testing in pages-s3-broker)
- Adds the VPCE variable to the federalist deploy pipeline

## security considerations
None

### CODE REVIEW

**Review by apburnes — COMMENTED** [review]
Should we update the config file from `federalist-config-template.yml` to `pages-config-template.yml`?

**Comment by drewbo** [comment]
I was leaving as is, specifically so we don't need to change the broker (pages ended up being just for testing) but I'm fine either way (one helps update the name, the other is easier to deploy I think)

**Comment by apburnes** [comment]
Sounds good. Let's leave the name change for a later date.

**Review by apburnes — APPROVED** [review]

**Review by rbogle — APPROVED** [review]
looks good to me!

**Pull request merged**
